# Request a ride.
service: wild-rydes-ride-requests

plugins:
  - serverless-python-requirements

custom:
  stage: "${opt:stage, env:SLS_STAGE, 'dev'}"
  profile: "${opt:aws-profile, env:AWS_PROFILE, env:AWS_DEFAULT_PROFILE, 'default'}"
  log_level: "${env:LOG_LEVEL, 'INFO'}"

  unicorn_hash_key: 'Name'
  unicorn_table_data: 'data/unicorns.json'

  pythonRequirements:
    # if using pyenv, make sure virtualenv was initialized to create python3.6
    # `pyenv virtualenv -p python3.6 <VERSION> <VIRTUALENV>`
    dockerizePip: false


provider:
  name: aws
  profile: ${self:custom.profile}
  stage: ${self:custom.stage}
  runtime: python3.6
  environment:
    LOG_LEVEL: ${self:custom.log_level}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource:
        Fn::GetAtt:
          - UnicornsTable
          - Arn


functions:
  RequestRide:
    handler: handlers/request_ride.handler
    description: "Request a ride."
    memorySize: 128
    timeout: 30
    environment:
      DYNAMODB_TABLE:
        Ref: UnicornsTable
      UNICORN_HASH_KEY: "${self:custom.unicorn_hash_key}"
    events:
      - http:
          path: /ride
          method: post
          cors: true

  LoadTable:
    handler: handlers/load_table.handler
    description: "Load an initial table."
    memorySize: 128
    timeout: 60
    environment:
      DYNAMODB_TABLE:
        Ref: UnicornsTable
      INITIAL_TABLE_DATA: "${self:custom.unicorn_table_data}"


resources:
  Resources:
    UnicornsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "${self:custom.unicorn_hash_key}"
            AttributeType: S
        KeySchema:
          - AttributeName: "${self:custom.unicorn_hash_key}"
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    LoadTable:
      Type: "Custom::ConfigFile"
      Properties:
        ServiceToken:
          Fn::GetAtt:
            - LoadTableLambdaFunction
            - Arn
        InvokeUrl:
          Fn::Join:
            - ""
            - - "https://"
              - Ref: ApiGatewayRestApi
              - ".execute-api."
              - Ref: AWS::Region
              - ".amazonaws.com/${self:custom.stage}"

