# <DESCRIBE SERVICE>
service: wild-rydes-ride-requests


plugins:
  - serverless-python-requirements

custom:
  stage: "${opt:stage, env:SLS_STAGE, 'dev'}"
  profile: "${opt:aws-profile, env:AWS_PROFILE, env:AWS_DEFAULT_PROFILE, 'default'}"
  log_level: "${env:LOG_LEVEL, 'INFO'}"

  launchdarkly_key: "${env:LAUNCHDARKLY_KEY}"

  pythonRequirements:
    # if using pyenv, make sure virtualenv was initialized to create python3.6
    # `pyenv virtualenv -p python3.6 <VERSION> <VIRTUALENV>`
    dockerizePip: false


provider:
  name: aws
  profile: ${self:custom.profile}
  stage: ${self:custom.stage}
  runtime: python3.6
  environment:
    LOG_LEVEL: ${self:custom.log_level}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource:
        Fn::GetAtt:
          - RidesTable
          - Arn


functions:
  RequestRide:
    handler: handlers/request_ride.handler
    description: "Request a ride."
    memorySize: 128
    timeout: 30
    environment:
      DYNAMODB_TABLE:
        Ref: RidesTable
      LAUNCHDARKLY_KEY:
        Ref: LaunchDarklyKey
    events:
      - http:
          path: /ride
          method: post
          cors: true


resources:
  Parameters:
    LaunchDarklyKey:
      Type: String
      Description: "LaunchDarkly SDK key"
      Default: "${self:custom.launchdarkly_key}"

  Resources:
    RidesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: RideId
            AttributeType: S
        KeySchema:
          - AttributeName: RideId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5


  Outputs:
    WildRydesApiInvokeUrl:
      Description: URL for the deployed wild rydes API
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api."
            - Ref: AWS::Region
            - ".amazonaws.com/${self:custom.stage}"
      Export:
        Name: "${self:service}-${self:provider.stage}-WildRydesApiUrl"

